### your site title here

title: Faraz Kaleem Malik
description: CS '26 @ UofT

baseurl: #name of GitHub repository
url: "https://farazkaleemmalik.cyou" #custom url to be used instead of GitHub repository
email: "webmaster@farazkaleemmalik.cyou"

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/:num/

# Social media links in footer
# twitter: "#"
linkedin: "farazkaleemmalik"
#stackoverflow: "20187265"
github: "numberisnan"
#researchgate: "#"
#orcid: "#"
#quora: "#"
#instagram: "#"
#facebook: "#"
#discord: "492024450825322498"
devpost: "farazkaleemmalik"


# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
